version: "3.8"

services:
  rtmp-server:
    image: my-rtmp-server
    build: .
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "5080:5080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TZ: Europe/Rome
    networks:
      - av-streaming

  web:
    image: httpd:2.4.54
    container_name: web
    ports:
      - "8088:80"
    volumes:
      - ./www/:/usr/local/apache2/htdocs/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TZ: Europe/Rome
    networks:
      - av-streaming

networks:
  av-streaming:
